name: Run E2E Tests

on:
  push:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-academia-pg:
        image: bitnami/postgresql:latest
        env:
          POSTGRESQL_USERNAME: linusacademia
          POSTGRESQL_PASSWORD: password123
          POSTGRESQL_DATABASE: academia
        ports: '8084:5432'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://linusacademia:password123@localhost:8084/academia?schema=public"